Dev jg
fairagro/middleware pull request #1
Opened 2023-11-28 16:14 UTC by jorgitogb

2023-11-28 16:20 UTC, Zalfsten requested changes

2023-11-28 16:20 UTC, Zalfsten commented on config.yml
Please remove the comments for bonares and edal

2023-11-28 16:20 UTC, Zalfsten commented on scrap_repo_test.ipynb
please not not commit this file

2023-11-28 16:20 UTC, Zalfsten commented on src/sitemap_parser_openagrar.py
please remove unneeded imports.

2023-11-29 09:28 UTC, jorgitogb commented on config.yml
done

2023-11-29 09:29 UTC, jorgitogb commented on scrap_repo_test.ipynb
done

2023-11-29 10:47 UTC, merged